In [60]:
# libraries

import pandas as pd
import numpy as np
import plotly.express as px
from pathlib import Path

In [45]:
#load data

data=  pd.read_csv('airbnb_train.csv')

In [6]:
#data visualization

data.head()

,id,name,description,neighborhood_overview,host_id,host_name,host_since,host_location,host_about,host_response_time,...,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month,city
0,246350,Private Room w/ Patio Downtown Toronto,This eclectic downtown apartment is comfortabl...,Corktown Toronto.,129487451,Ashley,2017-05-08,"Toronto, Canada","Hi I’m Ashley, I’m a mum of 2 little ones who ...",within an hour,...,2024-12-20,4.67,4.89,4.89,4.89,4.89,4.78,4.56,0.20,Toronto
1,11616,Habitación 5 -3,Enjoy the simplicity of this quiet and central...,NaN,18191427,David,2014-07-16,"Barcelona, Spain",NaN,within an hour,...,2025-02-19,4.00,4.60,4.00,4.00,4.40,4.60,4.00,2.27,Barcelona
2,70489,Royal Garden Waikiki Studio with Kitchinette -20%,Our condo is in the Club Wyndham building and ...,NaN,11916207,Alan,2014-02-03,"Campbell, CA","English guy married to a Philipinno lady, live...",within an hour,...,2024-02-17,4.78,5.00,4.89,5.00,4.89,5.00,5.00,0.22,Hawaii
3,89610,Spacious 3 bedroom Apartment,A spacious and beautiful 3 bedroom & 2 bathroo...,NaN,36818617,My London,2015-06-26,"London, United Kingdom",NaN,within an hour,...,2024-03-27,4.00,4.00,5.00,4.00,5.00,4.00,4.00,0.11,London
4,43669,Villa zafira with private pool,Leave behind any worries with this spacious an...,NaN,364602280,Panagiotis,2020-08-27,NaN,NaN,NaN,...,2024-07-27,5.00,5.00,5.00,5.00,5.00,4.00,5.00,0.19,Crete

In [46]:
#data visualization

data.describe()

,id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,...,estimated_occupancy_l365d,estimated_revenue_l365d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
count,208856.000000,2.088560e+05,208757.000000,208757.000000,208856.000000,208856.000000,208856.000000,208758.000000,208581.000000,208460.000000,...,97389.000000,97389.000000,168210.000000,168203.000000,168203.000000,168197.000000,168202.000000,168199.000000,168198.000000,168211.000000
mean,130910.285915,2.203708e+08,75.647236,112.152311,32.623370,-13.058838,3.949223,1.392807,1.649441,2.334880,...,84.823142,13745.557856,4.748524,4.777869,4.739318,4.830276,4.838841,4.777121,4.662327,1.433898
std,75665.531201,2.030446e+08,413.866681,583.862697,24.508293,71.513916,2.439907,0.792666,1.138836,1.832341,...,92.524149,21050.382155,0.393226,0.376937,0.403565,0.342427,0.344466,0.333982,0.424348,1.722879
min,1.000000,2.900000e+01,0.000000,0.000000,-43.440110,-159.714280,1.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.010000
25%,65293.500000,3.529497e+07,1.000000,2.000000,34.112403,-73.961360,2.000000,1.000000,1.000000,1.000000,...,0.000000,0.000000,4.670000,4.730000,4.670000,4.800000,4.820000,4.700000,4.570000,0.300000
50%,130964.500000,1.461081e+08,3.000000,4.000000,40.180001,2.159368,4.000000,1.000000,1.000000,2.000000,...,48.000000,5940.000000,4.860000,4.890000,4.860000,4.930000,4.950000,4.880000,4.760000,0.860000
75%,196472.500000,4.142567e+08,15.000000,20.000000,45.693964,14.776338,5.000000,2.000000,2.000000,3.000000,...,156.000000,19125.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,4.910000,2.000000
max,261893.000000,6.836695e+08,5282.000000,9988.000000,60.025359,153.634660,16.000000,50.000000,50.000000,121.000000,...,255.000000,255000.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,82.600000

In [51]:
data.isna().sum()

id                                  0
name                                0
description                      4873
neighborhood_overview          107040
host_id                             0
host_name                          92
host_since                         99
host_location                   53279
host_about                     100662
host_response_time              31961
host_response_rate              31961
host_acceptance_rate            17970
host_is_superhost                5841
host_neighbourhood             126725
host_listings_count                99
host_total_listings_count          99
host_verifications                 99
host_has_profile_pic               99
host_identity_verified             99
latitude                            0
longitude                           0
property_type                       0
room_type                           0
accommodates                        0
bathrooms                          98
bedrooms                          275
beds                              396
amenities                           0
price                               0
has_availability                 1833
availability_30                     0
availability_60                     0
availability_90                     0
availability_365                    0
number_of_reviews                   0
number_of_reviews_ltm               0
number_of_reviews_l30d              0
availability_eoy               111467
number_of_reviews_ly           111467
estimated_occupancy_l365d      111467
estimated_revenue_l365d        111467
first_review                    40645
last_review                     40645
review_scores_rating            40646
review_scores_accuracy          40653
review_scores_cleanliness       40653
review_scores_checkin           40659
review_scores_communication     40654
review_scores_location          40657
review_scores_value             40658
reviews_per_month               40645
city                                0
dtype: int64

In [53]:
#droping columns with NaN >= 15%

limite = 0.15  # 15%

data = data.drop(
    columns=data.columns[data.isna().mean() > limite]
)

In [54]:
data.describe()

,id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,availability_30,availability_60,availability_90,availability_365,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d
count,208856.000000,2.088560e+05,208757.000000,208757.000000,208856.000000,208856.000000,208856.000000,208758.000000,208581.000000,208460.000000,208856.000000,208856.000000,208856.000000,208856.000000,208856.000000,208856.000000,208856.000000,208856.000000
mean,130910.285915,2.203708e+08,75.647236,112.152311,32.623370,-13.058838,3.949223,1.392807,1.649441,2.334880,207.115836,14.723101,32.951397,52.897551,212.140101,42.512703,10.941242,0.662040
std,75665.531201,2.030446e+08,413.866681,583.862697,24.508293,71.513916,2.439907,0.792666,1.138836,1.832341,197.238695,11.329879,22.242444,32.667498,119.866805,85.146663,18.741042,1.513696
min,1.000000,2.900000e+01,0.000000,0.000000,-43.440110,-159.714280,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,65293.500000,3.529497e+07,1.000000,2.000000,34.112403,-73.961360,2.000000,1.000000,1.000000,1.000000,81.000000,2.000000,11.000000,23.000000,101.000000,1.000000,0.000000,0.000000
50%,130964.500000,1.461081e+08,3.000000,4.000000,40.180001,2.159368,4.000000,1.000000,1.000000,2.000000,136.000000,15.000000,37.000000,61.000000,233.000000,10.000000,3.000000,0.000000
75%,196472.500000,4.142567e+08,15.000000,20.000000,45.693964,14.776338,5.000000,2.000000,2.000000,3.000000,249.000000,26.000000,55.000000,84.000000,328.000000,44.000000,14.000000,1.000000
max,261893.000000,6.836695e+08,5282.000000,9988.000000,60.025359,153.634660,16.000000,50.000000,50.000000,121.000000,1000.000000,30.000000,60.000000,90.000000,365.000000,3117.000000,1290.000000,113.000000

In [55]:
data = data.dropna()

In [56]:
data.describe()

,id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,availability_30,availability_60,availability_90,availability_365,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d
count,180695.000000,1.806950e+05,180695.000000,180695.000000,180695.000000,180695.000000,180695.000000,180695.000000,180695.000000,180695.000000,180695.000000,180695.000000,180695.000000,180695.000000,180695.000000,180695.000000,180695.000000,180695.000000
mean,129762.258148,2.179864e+08,80.506500,117.963093,32.414415,-13.300949,3.976546,1.397905,1.655757,2.351410,205.780647,14.244130,32.099355,51.745223,209.654838,44.714060,11.670450,0.706196
std,76058.122456,2.022902e+08,431.260687,590.459802,24.722139,72.099885,2.459155,0.792532,1.142285,1.839718,195.641811,11.156802,21.963392,32.322397,119.089858,86.995676,19.097845,1.554157
min,1.000000,2.900000e+01,0.000000,0.000000,-43.440110,-159.714280,1.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,63804.500000,3.462910e+07,1.000000,2.000000,34.086440,-73.982670,2.000000,1.000000,1.000000,1.000000,80.000000,2.000000,10.000000,22.000000,99.000000,2.000000,0.000000,0.000000
50%,128455.000000,1.413663e+08,3.000000,4.000000,40.087556,0.063440,4.000000,1.000000,1.000000,2.000000,135.000000,14.000000,35.000000,59.000000,228.000000,12.000000,4.000000,0.000000
75%,196223.500000,4.108528e+08,16.000000,22.000000,45.645570,14.577905,5.000000,2.000000,2.000000,3.000000,247.000000,25.000000,53.000000,83.000000,324.000000,47.000000,15.000000,1.000000
max,261893.000000,6.834857e+08,5282.000000,9988.000000,60.025359,153.634660,16.000000,50.000000,50.000000,121.000000,1000.000000,30.000000,60.000000,90.000000,365.000000,3117.000000,1290.000000,113.000000

In [ ]:
#remove NaN reduced the data size from 208757 to 180695 ids

In [48]:
#separating 10% of data to se the word distribution
data_1 = data.sample(frac=0.1, random_state=42)

In [49]:
#ploting scatter to see the data

px.scatter(data_1, x = 'longitude', y ='latitude')

In [50]:
data_1_NAN = data_NAN.sample(frac=0.1, random_state=42)

#ploting scatter to see the data

px.scatter(data_1_NAN, x = 'longitude', y ='latitude')

#we can see taht droping NAN can reduce the diversity of the data, removing parts of west australia, mediteran sea, and part of US

In [57]:
# extracting only europe data

data_europe = data[
    (data['latitude'] >= 20) &
    (data['latitude'] <= 80) &
    (data['longitude'] >= -50) &
    (data['longitude'] <= 50)]

In [58]:
data_europe.isna().sum()

id                           0
name                         0
description                  0
host_id                      0
host_name                    0
host_since                   0
host_acceptance_rate         0
host_is_superhost            0
host_listings_count          0
host_total_listings_count    0
host_verifications           0
host_has_profile_pic         0
host_identity_verified       0
latitude                     0
longitude                    0
property_type                0
room_type                    0
accommodates                 0
bathrooms                    0
bedrooms                     0
beds                         0
amenities                    0
price                        0
has_availability             0
availability_30              0
availability_60              0
availability_90              0
availability_365             0
number_of_reviews            0
number_of_reviews_ltm        0
number_of_reviews_l30d       0
city                         0
dtype: int64

In [59]:
#separating america and australia to employ the model

data_america = data[
    (data['latitude'] >= -40) &
    (data['latitude'] <= 80) &
    (data['longitude'] >= -150) &
    (data['longitude'] <= -50)]

data_australia = data[
    (data['latitude'] >= -50) &
    (data['latitude'] <= -10) &
    (data['longitude'] >= 100) &
    (data['longitude'] <= 150)]

In [64]:
#saving data cleaned

# Creating folder
folder = Path("processed_data")
folder.mkdir(exist_ok=True)

In [65]:
data.to_csv(folder / "data.csv", index=False)
data_europe.to_csv(folder / "data_europe.csv", index=False)
data_america.to_csv(folder / "data_america.csv", index=False)
data_australia.to_csv(folder / "data_australia.csv", index=False)